apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ving.fullname" . }}
  labels:
    app: {{ include "ving.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "ving.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ving.name" . }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: {{ include "ving.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: django-secrets
