# Generated by Django 5.2.5 on 2025-08-31 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_add_prisabonnement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avreisested', models.CharField(max_length=255)),
                ('destinasjon', models.CharField(max_length=255)),
                ('pris', models.IntegerField()),
                ('url', models.URLField(max_length=500)),
                ('avreise_dato', models.DateField()),
                ('reiselengde', models.IntegerField()),
                ('dato_skrapt', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrisAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinasjon', models.CharField(max_length=200)),
                ('reiselengde', models.IntegerField()),
                ('avreise_dato', models.DateField()),
                ('maks_pris', models.IntegerField(blank=True, null=True)),
                ('sist_varslet_pris', models.IntegerField(blank=True, null=True)),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
                ('bruker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
