# Generated by Django 5.2.5 on 2025-08-31 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prisabonnement',
            name='maks_pris',
        ),
    ]
