# Generated by Django 5.2.5 on 2025-08-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_prisabonnement_maks_pris'),
    ]

    operations = [
        migrations.CreateModel(
            name='VingURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(help_text="Beskrivende navn, f.eks. 'Mallorca 8 dager'", max_length=200)),
                ('url', models.URLField()),
                ('aktiv', models.BooleanField(default=True, help_text='Brukes i scraping hvis aktivert')),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
