# Generated by Django 5.2.5 on 2025-11-08 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_vingurl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisabonnement',
            name='destinasjon',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vingdata',
            name='avreisested',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vingdata',
            name='destinasjon',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vingurl',
            name='navn',
            field=models.CharField(help_text="Beskrivende navn, f.eks. 'Mallorca 8 dager'", max_length=500),
        ),
        migrations.CreateModel(
            name='PersonligURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('lagt_til', models.DateTimeField(auto_now_add=True)),
                ('bruker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
