# Generated by Django 5.2.5 on 2025-11-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_prisabonnement_destinasjon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personligurl',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
