# Generated by Django 5.2.5 on 2025-11-08 21:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_personligurl_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='personligurl',
            name='navn',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
