# Generated by Django 5.2.5 on 2025-11-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_personligurl_navn'),
    ]

    operations = [
        migrations.AddField(
            model_name='vingdata',
            name='hjemreise_dato',
            field=models.DateField(blank=True, null=True),
        ),
    ]
