# Generated by Django 5.2.5 on 2025-11-10 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_vingdata_hjemreise_dato'),
    ]

    operations = [
        migrations.AddField(
            model_name='vingdata',
            name='vingurl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vingurl'),
        ),
    ]
