# Generated by Django 5.2.5 on 2025-11-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_vingdata_vingurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vingdata',
            name='vingurl',
        ),
    ]
