# Generated by Django 5.2.5 on 2025-11-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_vingdata_vingurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vingdata',
            name='reiselengde',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
