name: CI Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ving-runners
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print runner info
        run: |
          echo "Kjører på GitHub Runner Scale Set!"
          uname -a
          kubectl version --client || echo "kubectl ikke installert"
