name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Bygg og push Docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v3

      - name: Logg inn i registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Bygg og push image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/ArntBergin/ving:${{ github.sha }}
            ghcr.io/ArntBergin/ving:latest
          build-args: |
            PYTHON_VERSION=3.13

  deploy:
    name: Deploy til k3s via kubeconfig
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v3

      - name: Installer kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Sett opp kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Oppdater image i Deployment
        run: |
          kubectl set image deployment/ving-deployment \
            ving-container=ghcr.io/ArntBergin/ving:${{ github.sha }} \
            --record

      - name: Vent på rollout
        run: |
          kubectl rollout status deployment/ving-deployment