name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ghcr.io/arntbergin/ving:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build


    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.24.0'

    - name: Setup kubeconfig in writable folder
      run: |
        KUBE_DIR="$RUNNER_TEMP/.kube"
        mkdir -p "$KUBE_DIR"
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > "$KUBE_DIR/config"
        chmod 600 "$KUBE_DIR/config"
        echo "KUBECONFIG=$KUBE_DIR/config" >> $GITHUB_ENV

    - name: Test kubectl connectivity
      run: kubectl get nodes

    - name: Deploy manifests to K3s
      run: |
        # Sjekk at k8s-mappen finnes
        if [ -d "./k8s" ]; then
          kubectl apply -f k8s/
          kubectl rollout status deployment/ving-deployment
        else
          echo "No k8s/ folder found, skipping deployment"
        fi
