name: Build & Push & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Set image tag from commit
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ env.TAG }} \
            -t ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest \
            .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ env.TAG }}
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

      - name: Update values.yaml with new tag
        run: |
          sed -i "s|tag:.*|tag: ${TAG}|" helm-chart/values.yaml
          cat helm-chart/values.yaml

      - name: Deploy with Helm
        run: |
          helm upgrade --install ving ./helm-chart \
            --namespace ving \
            --set image.repository=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }} \
            --set image.tag=${{ env.TAG }} \
            --set image.pullPolicy=Always
