name: Build & Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Sjekk ut koden
      - name: Checkout repository
        uses: actions/checkout@v3

      # Logg inn på GitHub Container Registry med PAT
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      # Bygg Docker-image med riktig namespace (repo-owner/repo-navn)
      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/${{ toLower(github.repository_owner) }}/${{ github.event.repository.name }}:latest \
            .

      # Push Docker-image til GHCR
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ toLower(github.repository_owner) }}/${{ github.event.repository.name }}:latest
