name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted]   # lar ARC plukke jobben
    steps:
      - name: Sjekk ut repo
        uses: actions/checkout@v3

      - name: Logg inn på GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Bygg Docker-image
        run: docker build -t ghcr.io/arntbergin/ving:latest .

      - name: Push Docker-image
        run: docker push ghcr.io/arntbergin/ving:latest

      - name: Deploy til K3s
        run: |
          kubectl create namespace cicd || true
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
