name: Build, Push & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Sjekk ut koden
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Logg inn på GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      # 3️⃣ Sett lowercase owner og commit-hash som tag
      - name: Prepare variables
        run: |
          echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
          echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # 4️⃣ Sjekk om cronjob-relaterte filer er endret
      - name: Check if cronjob files changed
        id: croncheck
        run: |
          CHANGED=$(git diff --name-only origin/main...HEAD | grep -E 'Dockerfile.cron|helm-chart/templates/cronjob.yaml|source/mysite/main/management/commands/' || true)
          if [ -n "$CHANGED" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      # 5️⃣ Bygg webserver-image
      - name: Build webserver image
        run: |
          docker build \
            -f Dockerfile \
            -t ghcr.io/${OWNER_LC}/${REPO_NAME}:${TAG} \
            -t ghcr.io/${OWNER_LC}/${REPO_NAME}:latest \
            .

      # 5️⃣b Bygg cronjob-image (kun hvis endret)
      - name: Build cronjob image
        if: steps.croncheck.outputs.changed == 'true'
        run: |
          docker build \
            -f Dockerfile.cron \
            -t ghcr.io/${OWNER_LC}/${REPO_NAME}-cron:${TAG} \
            -t ghcr.io/${OWNER_LC}/${REPO_NAME}-cron:latest \
            .

      # 6️⃣ Push webserver image
      - name: Push webserver image
        run: |
          docker push ghcr.io/${OWNER_LC}/${REPO_NAME}:${TAG}
          docker push ghcr.io/${OWNER_LC}/${REPO_NAME}:latest

      # 6️⃣b Push cronjob image (kun hvis endret)
      - name: Push cronjob image
        if: steps.croncheck.outputs.changed == 'true'
        run: |
          docker push ghcr.io/${OWNER_LC}/${REPO_NAME}-cron:${TAG}
          docker push ghcr.io/${OWNER_LC}/${REPO_NAME}-cron:latest

      # 7️⃣ Oppdater values.yaml med ny tag for webserver
      - name: Update values.yaml (web)
        run: |
          sed -i "s|tag:.*|tag: ${TAG}|" helm-chart/values.yaml

      # 7️⃣b Oppdater values.yaml med ny tag for cronjob (kun hvis endret)
      - name: Update values.yaml (cronjob)
        if: steps.croncheck.outputs.changed == 'true'
        run: |
          sed -i "s|cronjob:[[:space:]]*[^:]*:[[:space:]]*.*|cronjob:\n  image:\n    repository: ghcr.io/${OWNER_LC}/${REPO_NAME}-cron\n    tag: ${TAG}|" helm-chart/values.yaml

      # 8️⃣ Vis oppdatert values.yaml
      - name: Show updated values.yaml
        run: cat helm-chart/values.yaml
