name: Build, Push & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Sjekk ut koden
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Logg inn på GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      # 3️⃣ Sett lowercase owner og commit-hash som tag
      - name: Prepare variables
        run: |
          echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
          echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # 4️⃣ Bygg webserver-image
      - name: Build webserver image
        run: |
          docker build \
            -f Dockerfile \
            -t ghcr.io/${OWNER_LC}/${REPO_NAME}:${TAG} \
            -t ghcr.io/${OWNER_LC}/${REPO_NAME}:latest \
            .

      # 4️⃣b Bygg cronjob-image
      - name: Build cronjob image
        run: |
          docker build \
            -f Dockerfile.cron \
            -t ghcr.io/${OWNER_LC}/${REPO_NAME}-cron:${TAG} \
            -t ghcr.io/${OWNER_LC}/${REPO_NAME}-cron:latest \
            .

      # 5️⃣ Push webserver image
      - name: Push webserver image
        run: |
          docker push ghcr.io/${OWNER_LC}/${REPO_NAME}:${TAG}
          docker push ghcr.io/${OWNER_LC}/${REPO_NAME}:latest

      # 5️⃣b Push cronjob image
      - name: Push cronjob image
        run: |
          docker push ghcr.io/${OWNER_LC}/${REPO_NAME}-cron:${TAG}
          docker push ghcr.io/${OWNER_LC}/${REPO_NAME}-cron:latest

      # 6️⃣ Oppdater values.yaml med ny tag for webserver
      - name: Update values.yaml (web)
        run: |
          sed -i "s|tag:.*|tag: ${TAG}|" helm-chart/values.yaml

      # 6️⃣b Oppdater values.yaml med ny tag for cronjob
      - name: Update values.yaml (cronjob)
        run: |
          sed -i "s|cronjob:[[:space:]]*[^:]*:[[:space:]]*.*|cronjob:\n  image:\n    repository: ghcr.io/${OWNER_LC}/${REPO_NAME}-cron\n    tag: ${TAG}|" helm-chart/values.yaml

      # 7️⃣ Vis oppdatert values.yaml
      - name: Show updated values.yaml
        run: cat helm-chart/values.yaml
