name: Build, Push & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Sjekk ut koden
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Logg inn på GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      # 3️⃣ Sett lowercase owner og commit-hash som tag
      - name: Prepare variables
        run: |
          echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
          echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # 4️⃣ Bygg image med commit-hash og latest
      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/${OWNER_LC}/${REPO_NAME}:${TAG} \
            -t ghcr.io/${OWNER_LC}/${REPO_NAME}:latest \
            .

      # 5️⃣ Push begge tags
      - name: Push Docker image
        run: |
          docker push ghcr.io/${OWNER_LC}/${REPO_NAME}:${TAG}
          docker push ghcr.io/${OWNER_LC}/${REPO_NAME}:latest

      # 6️⃣ Oppdater values.yaml med ny tag
      - name: Update values.yaml
        run: |
          sed -i "s|tag:.*|tag: ${TAG}|" helm-chart/values.yaml
          cat helm-chart/values.yaml
