name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted]   # lar ARC plukke jobben basert på repo/organization
    steps:
      # 1️⃣ Sjekk ut koden
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Logg inn på GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      # 3️⃣ Bygg Docker-image
      - name: Build Docker image
        run: docker build -t ghcr.io/arntbergin/ving:latest .

      # 4️⃣ Push Docker-image til GHCR
      - name: Push Docker image
        run: docker push ghcr.io/arntbergin/ving:latest

      # 5️⃣ Deploy til K3s
      - name: Deploy to K3s
        run: |
          # Lag namespace hvis det ikke finnes
          kubectl create namespace cicd || true
          # Apply deployment og service
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      # 6️⃣ Sjekk at deployment ble opprettet
      - name: Verify Deployment
        run: |
          kubectl get deploy -n cicd
          kubectl get svc -n cicd
