name: Build & Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Sjekk ut koden
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Logg inn på GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      # 3️⃣ Bygg Docker-image 
      - name: Build Docker image
        run: docker build -t ghcr.io/arntbergin/ving:latest .

      # 4️⃣ Push Docker-image til GHCR
      - name: Push Docker image
        run: docker push ghcr.io/arntbergin/ving:latest
