name: Build & Deploy

on:
  push:
    branches:
      - main  # kjør når du pusjer til main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut repo
        uses: actions/checkout@v3

      - name: Logg inn på GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
  
      - name: Bygg Docker-image
        run: |
          docker build -t ghcr.io/arntbergin/ving:latest .

      - name: Push Docker-image
        run: |
          docker push ghcr.io/arntbergin/ving:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.27.3

      - name: Deploy til K3s
        run: |
            printf "%s" "$KUBE_CONFIG" > /tmp/k3s.yaml
            kubectl --kubeconfig=/tmp/k3s.yaml create namespace cicd || true
            kubectl --kubeconfig=/tmp/k3s.yaml apply -f deployment.yaml
            kubectl --kubeconfig=/tmp/k3s.yaml apply -f service.yaml
        env:
            KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}