name: Test Runner

on:
  workflow_dispatch:   # lar deg trigge manuelt fra GitHub

jobs:
  test-runner:
    runs-on: [self-hosted, linux]   # matcher labels på dine ephemeral runners
    steps:
      - name: Sjekk ut repo
        uses: actions/checkout@v3

      - name: Echo test
        run: echo "Runner fungerer! 🚀"
