name: Test Helm i K3s

on:
  workflow_dispatch:

jobs:
  helm-test:
    runs-on: self-hosted

    steps:
      - name: Sjekk om Helm er installert
        run: |
          if ! command -v helm &> /dev/null; then
            echo "Helm ikke funnet – installerer..."
            curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          else
            echo "Helm er allerede installert."
          fi

      - name: Vis Helm-versjon
        run: helm version

      - name: Opprett testchart
        run: |
          helm create testchart
          ls testchart

      - name: Lint chart
        run: helm lint testchart

      - name: Dry-run installasjon
        run: helm install test-release testchart --dry-run --debug

      - name: Liste Helm releases
        run: helm list --all-namespaces
