name: Test self-hosted runner

on:
  workflow_dispatch:   # lar deg starte manuelt fra GitHub

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Installer kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
      - name: Sjekk kubectl-versjon
        run: kubectl version --client
      - name: Sjekk noder i klyngen
        run: kubectl get nodes -o wide
