name: Test self-hosted runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Installer curl og CA-sertifikater
        run: |
          apt-get update
          apt-get install -y curl ca-certificates
      - name: Last ned kubectl (fast versjon)
        run: |
          KUBECTL_VERSION=v1.30.4
          curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
          chmod +x kubectl
          mv kubectl /usr/local/bin/
      - name: Sjekk kubectl-versjon
        run: kubectl version --client
      - name: Sjekk noder i klyngen
        run: kubectl get nodes -o wide
