jobs:
  deploy:
    runs-on: self-hosted  # eller ubuntu-latest hvis du bruker hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "$KUBE_CONFIG" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - name: Test kubectl
        run: kubectl get nodes
