name: K3s Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "$KUBE_CONFIG" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - name: Test kubectl connectivity
        run: kubectl get nodes

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/  # Bytt ut med path til dine YAML-filer
          kubectl get all -o wide
