name: Test Self-Hosted Runner

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Sjekk runner
        run: echo "Runneren fungerer! 🚀"

      - name: Hent repo kode
        uses: actions/checkout@v4

      - name: Sjekk kubeconfig
        run: |
          kubectl --kubeconfig=/etc/rancher/k3s/k3s.yaml config current-context
          kubectl --kubeconfig=/etc/rancher/k3s/k3s.yaml get nodes -o wide

      - name: Deploy test nginx
        run: |
          kubectl --kubeconfig=/etc/rancher/k3s/k3s.yaml create deployment test-nginx --image=nginx || echo "Deployment finnes allerede"
          kubectl --kubeconfig=/etc/rancher/k3s/k3s.yaml rollout status deployment/test-nginx
          kubectl --kubeconfig=/etc/rancher/k3s/k3s.yaml get pods -l app=test-nginx -o wide
