name: Test Self-Hosted Runner

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Sjekk runner
        run: echo "Runneren fungerer! 🚀"

      - name: Hent repo kode
        uses: actions/checkout@v4

      - name: Sjekk kubeconfig
        env:
          KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        run: |
          kubectl config current-context
          kubectl get nodes -o wide

      - name: Deploy test nginx
        env:
          KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        run: |
          kubectl create deployment test-nginx --image=nginx || echo "Deployment finnes allerede"
          kubectl rollout status deployment/test-nginx
          kubectl get pods -l app=test-nginx -o wide
