name: K3s Deploy (Read-Only Safe)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # eller ubuntu-latest hvis du bruker hosted runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup kubeconfig in writable temp folder
        run: |
          KUBE_DIR="$RUNNER_TEMP/.kube"
          mkdir -p "$KUBE_DIR"
          echo "$KUBE_CONFIG" | base64 --decode > "$KUBE_DIR/config"
          chmod 600 "$KUBE_DIR/config"
          export KUBECONFIG="$KUBE_DIR/config"
          echo "KUBECONFIG=$KUBECONFIG" >> $GITHUB_ENV
          kubectl get nodes
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/   # Bytt ut med path til dine YAML-filer
          kubectl get all -o wide
