name: Test K3s Access

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Test kubeconfig direkte
        run: kubectl --kubeconfig=/etc/rancher/k3s/k3s.yaml get nodes -o wide
